FROM node:22.13.1-alpine AS dev

# Working directory inside the container
WORKDIR /app

# Copy package management files to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Ensure the "node" user owns the application files
RUN chown -R node:node /app

# Switch to the built-in non-root "node" user
USER node

# Expose the default Vite dev server port
EXPOSE 5173

# Start the application and make it accessible outside the container
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
